# This is an advanced workflow to show you how to use cache to accelerate CI job run
name: check_cross_account_permission

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  with_pip_cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # ref: https://github.com/actions/setup-python#caching-packages-dependencies
          cache: 'pip'
          cache-dependency-path: bootstrap/requirements.txt
      - name: install python dependencies
        run: pip install -r bootstrap/requirements.txt
      - name: check cross account permission
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: python bootstrap/check_cross_account_permission.py
