# This is an advanced workflow to show you how to use cache to accelerate CI job run
name: dummy_lambda_app

on:
  # ----------------------------------------------------------------------------
  # We automatically trigger CI job when there's a push event to the following branches
  #
  # Reference:
  # - Running your workflow only when a push to specific branches occurs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-to-specific-branches-occurs
  # ----------------------------------------------------------------------------
  workflow_dispatch:
  push:
    branches:
      - 'dummy_lambda_app/feature*'
      - 'dummy_lambda_app/feature*'
      - 'dummy_lambda_app/fix*'
      - 'dummy_lambda_app/doc*'
      - 'dummy_lambda_app/layer*'
      - 'dummy_lambda_app/lambda*'
      - 'dummy_lambda_app/release/'
      - 'dummy_lambda_app/cleanup*'

# Set common environment for all jobs and all steps
env:
  AWS_REGION: "us-east-1"
  DIR_PROJECT: "projects/dummy_lambda_app-project"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  job_0_build:
    runs-on: ubuntu-latest
    env:
      USER_ENV_NAME: devops
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          # --------------------------------------------------------------------
          # this role name has to match the ``github_action_open_id_connection.role_name`` field
          # in the ``bootstrap/config.json`` file
          # --------------------------------------------------------------------
          role-to-assume: arn:aws:iam::${{ secrets.DEVOPS_AWS_ACCOUNT_ID }}:role/monorepo-aws-github-oidc
          role-session-name: sample_role_session
          aws-region: ${{ env.AWS_REGION }}
      # ref: https://dev.to/aws-builders/deploy-to-aws-with-github-actions-and-aws-cdk-4m1e
      - name: 🛠 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: 💾 Install CDK in Node
        run: |
          npm install -g aws-cdk@2.111.0
          which cdk
          cdk --version
      - name: 🐍 Setup Python with pip cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # ref: https://github.com/actions/setup-python#caching-packages-dependencies
          cache: 'pip'
          cache-dependency-path: ${{ env.DIR_PROJECT }}/requirements-automation.txt
      - name: 💾 Install virtualenv, poetry Dependencies
        run: |
          pip install -r ${{ env.DIR_PROJECT }}/requirements-automation.txt
      - name: 🐍 Setup Python with poetry cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          # ref: https://github.com/actions/setup-python#caching-packages-dependencies
          cache: 'poetry'
          cache-dependency-path: ${{ env.DIR_PROJECT }}/poetry.lock
      - name: 🐍 💾 Create Virtual Environment and Install all dependencies
        working-directory: ${{ env.DIR_PROJECT }}
        run: |
          virtualenv -p python3.9 .venv
          poetry install
      #-------------------------------------------------------------------------
      #
      #-------------------------------------------------------------------------
      # Some unit test requires lambda source artifacts, so we have to build it before unit test
      - name: 🪜 Build Lambda Source Artifacts
        run: |
          echo done
      - name: 🧪 Run Code Coverage Test
        run: |
          echo done
      - name: === 🛑 END OF THE JOB ===
        run: echo "END OF THE JOB"

  job_1_deploy_to_sbx:
    uses: MacHu-GWU/monorepo_aws-project/.github/workflows/dummy_lambda_app_deploy.yml@main
    with:
      user_env_name: sbx
    needs: job_0_build
